services:
  app:
    build:
      context: .
    image: vat-report-frontend:latest
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT:-3000}
      API_PROTOCOL: ${API_PROTOCOL:-https}
      API_HOST: ${API_HOST:-api.garamol.com}
      API_PORT: ${API_PORT:-}
      API_BASE_URL: ${API_BASE_URL:-}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
